<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>LosTresMosqueteros</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\LosTresMosqueteros.Application\LosTresMosqueteros.Application.csproj" />
    <ProjectReference Include="..\LosTresMosqueteros.Domain.Tests\LosTresMosqueteros.Domain.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Productos\" />
  </ItemGroup>

</Project>
